DROP FUNCTION GET_TOTAL_PAYMENT; 

--#SET TERMINATOR @ 
CREATE FUNCTION GET_TOTAL_PAYMENT (transactionNo VARCHAR(8))
RETURNS DOUBLE 
NO EXTERNAL ACTION 
BEGIN ATOMIC 
    RETURN 
        SELECT SUM(amount) 
        FROM payment 
        WHERE transactionNo = payment.transno;
END@
--#SET TERMINATOR ;

SELECT DISTINCT GET_TOTAL_PAYMENT('TR000092') "TOTAL TRANS PAYMENT"
FROM payment;